[package]
name = "mobilenet"
version = "0.1.0"
authors = ["Michael Yuan <michael@secondstate.io>"]
edition = "2018"

[dependencies]
wasm-bindgen = "=0.2.61"
ssvm_tensorflow_interface = "^0.1.3"
base64 = "0.12.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "=1.0.44"
